config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :restaurants do 
    resources :reviews 
    end

    resources :reviews do 
      resources :endorsements
    end
  

  root 'restaurants#index'

end

app/models/endorsement.rb
class Endorsement < ActiveRecord::Base
  belongs_to :review
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :reviews, dependent: :destroy
	validates :name, length: {minimum: 3}, uniqueness: true
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/


	def average_rating 
		return "N/A" if reviews.none?
		reviews.average(:rating)
	end
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :restaurant
	validates :rating, inclusion: { in: 1..5 }
	has_many :endorsements
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook, :twitter]

    def self.from_omniauth_facebook(auth)
		  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
		    user.email = auth.info.email
		    user.password = Devise.friendly_token[0,20]
		    # user.name = auth.info.name   # assuming the user model has a name
		    # user.image = auth.info.image # assuming the user model has an image
	  	end
		end

		def self.from_omniauth_twitter(auth)
		  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
		    user.email = auth.info.nickname + "@twitter.com"
		    user.nickname = auth.info.nickname
		    user.password = Devise.friendly_token[0,20]
		    # user.name = auth.info.name   # assuming the user model has a name
		    # user.image = auth.info.image # assuming the user model has an image
	  	end
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController
		include ActionView::Helpers::TextHelper

	def create 
		@review = Review.find(params[:review_id])
		@review.endorsements.create
		render json: {new_endorsement_count: "#{pluralize(@review.endorsements.count, "endorsement")}"}
	end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

	def index
		@restaurants = Restaurant.all
	end

	def new 
	 @restaurant = Restaurant.new
	end

	def edit
		@restaurant = Restaurant.find(params[:id])
	end
	
	def show
		@restaurant = Restaurant.find(params[:id])
	end
	
	def create
		@restaurant = Restaurant.create(params[:restaurant].permit(:name, :description, :image))
		if @restaurant.save
			redirect_to restaurants_path
		else
			render 'new'	
		end
	end

	def update
		@restaurant = Restaurant.find(params[:id])
		@restaurant.update(params[:restaurant].permit(:name, :description))
		redirect_to restaurants_path
	end

	def destroy
		@restaurant = Restaurant.find(params[:id])
		@restaurant.destroy
		flash[:notice] = 'Restaurant deleted successfully'
		redirect_to restaurants_path
	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	def new
		@restaurant = Restaurant.find(params[:restaurant_id])
		@review = Review.new
	end

	def create 
		@restaurant = Restaurant.find(params[:restaurant_id])
		@restaurant.reviews.create(params[:review].permit(:rating, :review))
		redirect_to restaurants_path
	end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

	def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth_facebook(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter

        @user = User.from_omniauth_twitter(request.env["omniauth.auth"])
        if @user.persisted?         
          sign_in_and_redirect @user, :event => :authentication
          set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
        else
          session["devise.twitter_data"] = request.env["omniauth.auth"]
          redirect_to new_user_registration_url
        end
    end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper

	def star_rating(rating)
		return rating unless rating.respond_to?(:round) 
		remainder = (5 - rating.round) 
		"★" * rating.round + ("☆" * remainder)
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YelpClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset='utf8'>
</head>
<body>
<% if user_signed_in? %>
	<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
<%else%>
	<%= link_to "Sign In", new_user_session_path %>
	<%= link_to "Sign Up", new_user_registration_path %>
<%end%>
<%=notice %>
<%= yield %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/restaurants/_form.html.erb
 <% if @restaurant.errors.any? %>
	<div id="errors_explaination">
		<h2><%=pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved: </h2>
		<ul>
			<% @restaurant.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<%end%>
		</ul>
	</div>
<% end %>

<%= form_for @restaurant, :html => { :multipart => true } do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :description %>
	<%= f.text_field :description %>
	<%= f.label :image %>
	<%= f.file_field :image %>
	<%= f.submit %>
<%end%> 

app/views/restaurants/edit.html.erb
<%= render 'form' %>

app/views/restaurants/index.html.erb
<%if @restaurants.any? %>
	<% @restaurants.each do |restaurant| %>
		<h2> <%=link_to "#{ restaurant.name}", restaurant_path(restaurant) %> </h2>
		<%=image_tag restaurant.image.url(:thumb) %>
		<%=link_to "Edit #{ restaurant.name }", edit_restaurant_path(restaurant) %>
		<%=link_to "Delete #{ restaurant.name }", restaurant_path(restaurant), method: :delete %>
		<%=link_to "Review #{ restaurant.name}", new_restaurant_review_path(restaurant) %>
		<ul>
			<% restaurant.reviews.each do |review| %>
				<li> <%= "#{review.review}, (#{review.rating}),"%><em> posted: <%=time_ago_in_words(review.created_at)%> ago </em>
				<%= link_to 'Endorse this review', review_endorsements_path(review), class: 'endorsements-link' %>
				<span class='endorsements_count'>
					<%= pluralize(review.endorsements.count, 'endorsement') %>
				</span></li>
			<%end%>
			 <h3>Average rating: <%=star_rating(restaurant.average_rating) %></h3>
		</ul>	

		<%end%>
<%else %>
	No restaurants yet!
<% end %>

<%= link_to 'Add a restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<%= form_for @restaurant do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<%=image_tag @restaurant.image.url(:medium) %>

<p><%= @restaurant.description %></p>

<%= link_to 'Return to menu', restaurants_path %>

app/views/reviews/new.html.erb
<%= form_for [@restaurant, @review] do |f| %>
<%= f.label :review %>
<%= f.text_area :review %>

<%=f.label :rating %>
<%=f.select :rating, (1..5) %>
<%=f.submit 'Leave review' %>
<% end %>